function makeArray(len)
{ 
 for (var i = 0; i < len; i++) this[i] = null;
 this.length = len;
}
var dailyEvents = new makeArray(7);
 dailyEvents[0] = "Today is Sunday! <i>The Move Tutor is in Goldenrod City! Let him teach a new move to your Pokemon.</i> A Lady is passing out TM 21 and 27 in the Goldenrod Department Store. Sunny is giving away a Magnet in Route 37. ALL ABOARD! The S.S. Aqua is leaving Vermilion City. Kanpo and Haircut Brother 2 is in the Goldenrod Underground. Pokemon March is playing on Radio 7.5.";
 dailyEvents[1] = "Today is Monday! There will be a spectacular Clefairy Dance Tonight in Mt. Moon. Your Rival is waiting to battle you in Indigo Plateau Today. Monica Will give Away a Sharp Beak Today in Route 40. ALL ABOARD! The S.S. Aqua is leaving Olivine City Today. Pokemon Lullaby is playing on Radio 7.5 today. The Shop is open in the Goldenrod Underground all of Today.";
 dailyEvents[2] = "Today is Tuesday! Tuscany will give away a Pink Bow in Route 29. Make Your Pokemon Look Handsome. Haircut Brother 1 is in the Goldenrod Underground today. There will be a Huge Bug-Catching Event in the National Park Today. WIN PRIZES and capture lots of Pokemon! If you beat your Rival in a Pokemon Battle in Mt. Moon, he Will Meditate in the Dragon's Den Today. Pokemon March is playing on Radio 7.5 today.";
 dailyEvents[3] = "Today is Wednesday! <i>The Move Tutor is in Goldenrod City! Let him teach a new move to your Pokemon.</i> Your Rival is waiting to battle you in Indigo Plateau Today. Wesley will give away a Black Belt near the Lake of Rage today. ALL ABOARD! The S.S. Aqua is leaving Vermilion City Today. Haircut Brother 2 is in the Goldenrod Underground today. Pokemon Lullaby is playing on Radio 7.5 today.";
 dailyEvents[4] = "Today is Thursday! Arthur will give you a Hard Stone in Route 26. Make Your Pokemon Look Handsome. Haircut Brother 1 is in the Goldenrod Underground today. There will be a Huge Bug-Catching Event in the National Park Today. WIN PRIZES and capture lots of Pokemon! If you beat your Rival in a Pokemon Battle in Mt. Moon, he Will Meditate in the Dragon's Den Today. Pokemon March is playing on Radio 7.5 today.";
 dailyEvents[5] = "Today is Friday! Feelin' Lucky? Check your Pokemons' ID. If they match the Lucky Radio Tower Number you'll win a sweet prize. Lapras is in the Union Cave Today. Capture it! On Route 32 Frieda will give you a Poison Barb. ALL ABOARD! The S.S. Aqua is leaving Olivine City Today. Make Your Pokemon Look Handsome. Haircut Brother 2 is in the Goldenrod Underground today. Pokemon Lullaby is playing on Radio 7.5 today.";
 dailyEvents[6] = "Today is Saturday! Santos will give you a Spell Tag Today in Blackthorn City. Kanpo is in the Goldenrod Underground today. Make Your Pokemon Look Handsome. Haircut Brother 1 is in the Goldenrod Underground today. There will be a Huge Bug-Catching Event in the National Park Today. WIN PRIZES and capture lots of Pokemon! Pokemon March is playing on Radio 7.5 today.";
var monthEvents = new makeArray(12);
 monthEvents[0] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[1] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[2] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[3] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. Daylight Savings Time Begins This Month in America. Make sure you set your clocks forward. HAVE A GOOD DAY!";
 monthEvents[4] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[5] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[6] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[7] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[8] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[9] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. Daylight Savings Time Ends This Month in America. Make Sure You Set Your Clocks Back. HAVE A GOOD DAY!";
 monthEvents[10] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAVE A GOOD DAY!";
 monthEvents[11] = "The Shop is open today in Mt. Moon morning and day. Make Your Pokemon Very Happy. Groom it in Blue's House in Pallet Town from 3-4 PM. There will be a Guard waiting to battle you Tonight in Routes 34 & 35. HAPPY HOLIDAYS EVERYONE!";
var now = new Date();
var day = now.getDay();
var month = now.getMonth();
document.write(dailyEvents[day] + " " + monthEvents[month]);